---
root: true
env:
  browser: true
  node: true
extends: airbnb-base
parser: babel-eslint
plugins:
- filenames
- import
- html
rules:
  no-unused-vars: 'off'
  filenames/match-regex:
  - 2
  - "^[a-z0-9_]+$"
  import/no-commonjs: error
  no-multiple-empty-lines:
  - error
  - max: 1
  promise/catch-or-return: 'off'
  no-underscore-dangle:
  - error
  - allow:
    - __
  import/no-extraneous-dependencies: 'off'
  no-debugger: 'off'
  arrow-parens: 0
  space-before-function-paren: 0
  function-paren-newline: 0
globals: {}
