extends: '@gitlab'
rules:
  # The contents of svgpreviewer/** are exempt from requiring production dependencies
  # because the previewer is a development tool and not an end product
  import/no-extraneous-dependencies:
    - 'error'
    - devDependencies: ['svgpreviewer/**']
      optionalDependencies: false
